//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocScan.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ENG1\\ENG1;Initial Catalog=SalesOrderScan;User ID=scanner;Password=b3@" +
            "mM3U9")]
        public string SalesOrderScanConnectionString {
            get {
                return ((string)(this["SalesOrderScanConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Dsn=Sage 100 2014;uid=swk;pwd=indigo01")]
        public string SageConnectionString {
            get {
                return ((string)(this["SageConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Dsn=SOTAMAS90;uid=swk;company=UMD;pwd=indigo01;description=MAS 90 4.0 ODBC Driver;directory=D:\Sage\Version_2014\MAS90;prefix=D:\Sage\Version_2014\MAS90\SY\, D:\Sage\Version_2014\MAS90\==\;viewdll=D:\Sage\Version_2014\MAS90\Home\;logfile=\PVXODBC.LOG;remotepvkiohost=MAS3;remotepvkioport=20222;cachesize=4;dirtyreads=1;burstmode=1;striptrailingspaces=1;server=NotTheServer")]
        public string SOTAMASConnectionString {
            get {
                return ((string)(this["SOTAMASConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ENG1;Initial Catalog=SalesOrderScan;Persist Security Info=True;User I" +
            "D=scanner;Password=b3@mM3U9")]
        public string SalesOrderScanConnectionString1 {
            get {
                return ((string)(this["SalesOrderScanConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ENG1\\ENG1;Initial Catalog=SalesOrderScan;Persist Security Info=True;U" +
            "ser ID=scanner;Password=b3@mM3U9;Context Connection=False")]
        public string SalesOrderScanConnectionString2 {
            get {
                return ((string)(this["SalesOrderScanConnectionString2"]));
            }
        }
    }
}
