//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabelPrinter.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Dsn=SAGE 100 2014;uid=swk;company=UMD;pwd=indigo01;description=MAS 90 4.0 ODBC Driver;directory=D:\Sage\Version_2014\MAS90;prefix=D:\Sage\Version_2014\MAS90\SY\, D:\Sage\Version_2014\MAS90\==\;viewdll=D:\Sage\Version_2014\MAS90\Home\;logfile=\PVXODBC.LOG;remotepvkiohost=MAS3;remotepvkioport=20222;cachesize=4;dirtyreads=1;burstmode=1;striptrailingspaces=1;server=NotTheServer")]
        public string dbConnection {
            get {
                return ((string)(this["dbConnection"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F:\\IT-BarTender\\NiceLabel_ProductionLabels")]
        public string labelsPath {
            get {
                return ((string)(this["labelsPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SQL1\\SQL2016;Initial Catalog=Labels;User ID=labelPrinter;Password=pri" +
            "ntThat")]
        public string SqlDbConnection {
            get {
                return ((string)(this["SqlDbConnection"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal QtyOverride {
            get {
                return ((decimal)(this["QtyOverride"]));
            }
            set {
                this["QtyOverride"] = value;
            }
        }
    }
}
