'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Jumbotron3
    
    '''<summary>
    '''nip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents nip As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''non control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents non As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''cert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cert As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''build control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents build As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''test1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents test1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''test2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents test2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''paint control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents paint As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
