'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class JumboTronNorth
    
    '''<summary>
    '''nip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents nip As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''tst2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tst2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ncw control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ncw As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''cw control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cw As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
