'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class JumboTronMain
    
    '''<summary>
    '''bld control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bld As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''tst control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tst As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''tst2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tst2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''pnt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnt As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
