//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchForScans.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DocScanArchiveEntities : DbContext
    {
        public DocScanArchiveEntities()
            : base("name=DocScanArchiveEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FileStorage> FileStorages { get; set; }
        public virtual DbSet<SalesOrderArchive> SalesOrderArchives { get; set; }
        public virtual DbSet<SetupInfo> SetupInfoes { get; set; }
        public virtual DbSet<WorkOrderArchive> WorkOrderArchives { get; set; }
    }
}
