//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchForScans.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrderArchive
    {
        public int Id { get; set; }
        public string SalesOrderNumber { get; set; }
        public string VendorName { get; set; }
        public Nullable<System.DateTime> SODate { get; set; }
        public System.DateTime ScanDate { get; set; }
        public string FileName { get; set; }
        public string FileType { get; set; }
        public int FileID { get; set; }
    }
}
